- hosts: ansible
  connection: local
  vars:
    aws_regions: 
    - us-east-1
    - us-west-1
    - us-west-2
  tasks:
  - name: create dirs
    file: path="{{ inv_dir }}/{{ item }}" state=directory
    with_items: "{{ aws_regions }}"
  - name: describe-instances
    #shell: "aws ec2 describe-instances --profile {{ aws_profile }}  --region {{ item }} | python -c'import fileinput, json;print(json.dumps(json.loads(\"\".join(fileinput.input())),sort_keys=True, indent=4))' > {{ inv_dir }}/{{ item }}/instances.json"
    #shell: "aws ec2 describe-instances --profile {{ aws_profile }}  --region {{ item }} | jsonlint -s > {{ inv_dir }}/{{ item }}/instances.json"
    shell: "aws ec2 describe-instances --profile {{ aws_profile }}  --region {{ item }} --output text > {{ inv_dir }}/{{ item }}/instances.txt"
    with_items: "{{ aws_regions }}"
  - name: describe-groups
    #shell: "aws ec2 describe-security-groups --profile {{ aws_profile }} --region {{ item }} | python -c'import fileinput, json;print(json.dumps(json.loads(\"\".join(fileinput.input())),sort_keys=True, indent=4))' > {{ inv_dir }}/{{ item }}/groups.json"
    shell: "aws ec2 describe-security-groups --profile {{ aws_profile }} --region {{ item }} --output text > {{ inv_dir }}/{{ item }}/groups.txt"
    with_items: "{{ aws_regions }}"
  - name: describe-volvumes
    #shell: "aws ec2 describe-volumes --profile {{ aws_profile }} --region {{ item }} |python -c'import fileinput, json;print(json.dumps(json.loads(\"\".join(fileinput.input())),sort_keys=True, indent=4))'  > {{ inv_dir }}/{{ item }}/volumes.json"
    shell: "aws ec2 describe-volumes --profile {{ aws_profile }} --region {{ item }} --output text  > {{ inv_dir }}/{{ item }}/volumes.txt"
    with_items: "{{ aws_regions }}"
  - name: describe-elb
    #shell: "aws elb describe-load-balancers --profile {{ aws_profile }} --region {{ item }} | python -c'import fileinput, json;print(json.dumps(json.loads(\"\".join(fileinput.input())),sort_keys=True, indent=4))'  > {{ inv_dir }}/{{ item }}/elbs.json"
    shell: "aws elb describe-load-balancers --profile {{ aws_profile }} --region {{ item }} --output text  > {{ inv_dir }}/{{ item }}/elbs.txt"
    with_items: "{{ aws_regions }}"
